services:
  frontend:
    image: enf3rno/bowling_frontend:latest
    ports:
    - 8080:8080
  api:
    image: enf3rno/bowling_api:latest
    ports:
      - "8000:8000"
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my-datavolume:/var/lib/mysql
  # mysqlcli:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #   ports:
  #     - 8081:8080
      # Used for webui gui
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
volumes:
  my-datavolume: